'use strict';
const E=TarotReader,D=TAROT_DECK,F=FortuneEngine,$=id=>document.getElementById(id),KEY='arcana-reflection-v3';let state={history:{},active:null},current=null,restored=false,mode='tarot',topic='love',spread='auto',allowReversed=true,redrawChoice='single',birthEra='be',birthMonth=1,wallpaperTopic='auto',motion=0,revealAction=null,lastWallpaper=null;
document.addEventListener('contextmenu',event=>{if(event.target.closest&&event.target.closest('.card-art,.wallpaper-preview,.falling-stick'))event.preventDefault();});
try{const saved=JSON.parse(sessionStorage.getItem(KEY));if(saved&&saved.history&&typeof saved.history==='object')state=saved;}catch{}
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;const pause=ms=>new Promise(r=>setTimeout(r,reduced()?0:ms));
function save(){try{sessionStorage.setItem(KEY,JSON.stringify(state));}catch{status('เบราว์เซอร์ไม่อนุญาตให้บันทึกผลในแท็บนี้ ผลอาจไม่คงอยู่เมื่อรีเฟรช');}}
function status(t=''){$('status').textContent=t;}
async function askAI(payload){
 const configured=(window.ARCANA_AI_ENDPOINT||'').trim(),endpoint=configured?(/\/api\/respond\/?$/.test(configured)?configured:configured.replace(/\/+$/,'')+'/api/respond'):'api/respond';
 if(!window.ARCANA_AI_ENDPOINT&&location.hostname.endsWith('github.io'))throw Error('AI ยังไม่เปิดบนเว็บทดสอบ');
 const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
 let data;try{data=await response.json();}catch{throw Error('AI ยังไม่พร้อมบนเว็บไซต์นี้');}
 if(!response.ok)throw Error(data.error||'AI ยังตอบไม่ได้');
 return data;
}
function node(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function choices(id,items,selected,onChange){const group=$(id);group.replaceChildren(...items.map(([v,label])=>{const b=node('button',label);b.type='button';b.setAttribute('aria-pressed',String(v===selected));b.addEventListener('click',()=>{group.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');onChange(v);});return b;}));}
function portrait(card,reversed=false){const p=node('div',undefined,'portrait'+(reversed?' reversed':'')),a=node('div',undefined,'card-art');a.style.backgroundImage='url("assets/tarot-sheet-'+card.sheet+'.webp")';a.style.backgroundPosition=((card.cell%4)*100/3)+'% '+(Math.floor(card.cell/4)*100)+'%';const label=node('div',card.name_th,'face-label');if(card.arcana==='major')label.prepend(node('small',['0','I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX','XXI'][card.index]||''));label.append(node('small','('+card.name_en+')'+(reversed?' · กลับหัว':'')));p.append(a,label);return p;}
function cup(shaking=false){const c=node('div',undefined,'siamsi-cup'+(shaking?' shaking':''));for(let i=0;i<7;i++){const stick=node('i');stick.style.setProperty('--i',i);c.append(stick);}return c;}
[2,17,18].forEach((idx,i)=>{const c=node('div',undefined,'hero-card '+['card-left','card-center','card-right'][i]);c.append(portrait(D[idx]));$('hero-cards').append(c);});
choices('topic',[['general','ภาพรวม'],['love','ความรัก'],['work','การงาน'],['money','การเงิน'],['self','ดูแลใจ']],topic,v=>topic=v);
choices('spread',[['auto','เลือกให้ฉัน'],['single','หนึ่งใบ'],['three_card','เส้นทางสามใบ'],['decision_3','ทางเลือกสามใบ'],['five_card','สำรวจห้าใบ']],spread,v=>spread=v);
choices('birth-era',[['be','พ.ศ.'],['ce','ค.ศ.']],birthEra,v=>{birthEra=v;$('birth-year').placeholder=v==='be'?'เช่น 2543':'เช่น 2000';});
choices('birth-month',['ม.ค.','ก.พ.','มี.ค.','เม.ย.','พ.ค.','มิ.ย.','ก.ค.','ส.ค.','ก.ย.','ต.ค.','พ.ย.','ธ.ค.'].map((x,i)=>[i+1,x]),birthMonth,v=>birthMonth=v);
choices('wallpaper-topic',[['auto','ให้ภาพเลือกฉัน'],['calm','พักใจ'],['love','ความรัก'],['prosperity','ความมั่นคง'],['clarity','การงาน']],wallpaperTopic,v=>{wallpaperTopic=v;$('wallpaper-start').textContent=v==='auto'?'สุ่มภาพสำหรับคุณ ◇':'เปิดภาพตามความตั้งใจ ◇';});
$('reversed').addEventListener('click',()=>{allowReversed=!allowReversed;$('reversed').setAttribute('aria-pressed',String(allowReversed));});
$('today-label').textContent=new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'short',timeZone:'Asia/Bangkok'}).format(new Date());
const modeCopy={tarot:['ไพ่ 78 ใบ · เรื่องราวนับไม่ถ้วน','เมื่อใจนิ่งพอ','คำตอบจะชัดขึ้น','บางเรื่องไม่ต้องรีบหาคำตอบ ให้ไพ่เป็นพื้นที่เล็ก ๆ ที่คุณได้มองความรู้สึกและทางเลือกของตัวเอง','ทุกใบมีเรื่องราว ทุกเรื่องมีทางเลือก'],siamsi:['หนึ่งไม้ที่หล่นลง · หนึ่งมุมที่ได้เห็น','ตั้งจิตให้สงบ','รับถ้อยคำของวันนี้','ปล่อยเสียงรอบตัวให้เบาลง แล้วฟังบทกลอนและคำอ่านที่ชวนคุณมองเรื่องในใจด้วยสายตาใหม่','ความหมายที่ดี เริ่มจากใจที่เปิดรับ'],birthday:['วันแรกของคุณ · จังหวะเฉพาะตัว','รู้จักจังหวะชีวิต','อ่อนโยนกับตัวเอง','สำรวจบุคลิกและสิ่งที่อยากพัฒนาผ่านการตีความวันเกิด เป็นอีกมุมหนึ่งให้คุณได้รู้จักตัวเอง','ทุกคนมีจังหวะที่เติบโตได้ในแบบของตัวเอง'],daily:['หนึ่งวัน · หนึ่งใบ · หนึ่งความตั้งใจ','ให้วันนี้เริ่มต้น','ด้วยใจที่ชัดเจน','เก็บถ้อยคำหนึ่งชุดไว้เป็นเพื่อนตลอดวัน แล้วค่อย ๆ เลือกสิ่งเล็ก ๆ ที่อยากทำให้ตัวเอง','กลับมาอ่านผลเดิมได้ตลอดวันนี้'],wallpaper:['ภาพมงคล · ความตั้งใจที่อยู่ใกล้ตัว','เก็บพลังที่รัก','ไว้ในทุกวัน','ภาพศิลป์จากสัญลักษณ์มงคลตามความเชื่อ เพื่อเป็นกำลังใจและสิ่งเตือนใจในทุกครั้งที่เปิดหน้าจอ','ความเชื่อที่งดงาม คู่กับการลงมือทำ']};
modeCopy.chat=['พื้นที่รับฟัง · คำปรึกษาเบื้องต้น','เล่าได้ตามสบาย','เราค่อย ๆ คิดด้วยกัน','เขียนเรื่องที่กำลังหนักใจ แล้วให้ AI ช่วยเรียบเรียงความคิดและมองทางเลือกอย่างระมัดระวัง','พื้นที่สำหรับรับฟังและหาทางก้าวต่อ'];
function show(id){['intro','ritual','result','crisis','other-result'].forEach(x=>{$(x).hidden=x!==id;$(x).classList.remove('vanishing');});$(id).classList.add('appearing');window.scrollTo({top:0,behavior:reduced()?'instant':'smooth'});}
function switchMode(next){motion++;mode=next;state.mode=next;save();status();document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));document.querySelectorAll('[data-form]').forEach(e=>e.hidden=e.dataset.form!==mode);const c=modeCopy[mode];$('mode-eyebrow').textContent=c[0];$('mode-title').replaceChildren(document.createTextNode(c[1]),document.createElement('br'),node('span',c[2],'gold-text'));$('mode-lead').textContent=c[3];$('stage-caption').textContent=c[4];$('hero-cards').hidden=!['tarot','daily'].includes(mode);$('hero-emblem').hidden=['tarot','daily'].includes(mode);$('hero-emblem').replaceChildren(mode==='siamsi'?cup():node('span',mode==='birthday'?'☉':'◇'));show('intro');}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>switchMode(b.dataset.mode)));
function crisis(){motion++;current=null;state.active=null;save();$('drawn-cards').replaceChildren();$('reading-output').replaceChildren();$('ritual-backs').replaceChildren();show('crisis');}
function input(){return {question:$('question').value.trim(),context:$('context').value.trim(),topic,spread_choice:spread,allowReversed,language:'th'};}
function resetRitual(title,question){$('ritual-title').textContent=title;$('ritual-question').textContent=question||'';$('ritual-animation').replaceChildren();$('ritual-animation').hidden=false;$('ritual-backs').replaceChildren();$('ritual-backs').hidden=false;$('ritual-backs').classList.remove('choice-grid','spread-slots');$('ritual').classList.remove('tarot-selection');$('ritual-selection-count').hidden=true;$('reveal').hidden=true;$('reading-loader').hidden=true;$('siamsi-shake-controls').hidden=true;revealAction=null;show('ritual');}
function flipCard(d,i){const outer=node('div',undefined,'ritual-card');outer.style.setProperty('--i',i);const inner=node('div',undefined,'ritual-card-inner'),front=node('div',undefined,'ritual-front'),back=node('div',undefined,'ritual-back');front.setAttribute('aria-hidden','true');front.append(portrait(D.find(c=>c.id===d.id),d.reversed));inner.append(back,front);outer.append(inner);outer.setAttribute('aria-label','ไพ่ใบที่ '+(i+1));return outer;}
async function tarotRitual(draw,question,onComplete){const token=++motion;resetRitual('กำลังสับไพ่ให้คุณ',question);const stack=node('div',undefined,'shuffle-stack');for(let i=0;i<5;i++){const c=node('div',undefined,'shuffle-card');c.style.setProperty('--i',i);stack.append(c);}$('ritual-animation').append(stack);await pause(1700);if(token!==motion)return;stack.classList.add('vanishing');await pause(400);if(token!==motion)return;$('ritual-animation').hidden=true;$('ritual-title').textContent='เมื่อพร้อม ค่อยเปิดไพ่ของคุณ';$('ritual-backs').replaceChildren(...draw.map(flipCard));$('reveal').hidden=false;$('reveal').disabled=false;revealAction=async()=>{if(token!==motion)return;$('reveal').disabled=true;$('reveal').hidden=true;$('ritual-backs').querySelectorAll('.ritual-card').forEach(c=>{c.classList.add('open');c.querySelector('.ritual-front').removeAttribute('aria-hidden');});await pause(1150+draw.length*140);if(token!==motion)return;$('reading-loader').hidden=false;await pause(850);if(token!==motion)return;onComplete();};}
async function selectionRitual(record,onComplete){
 const token=++motion,needed=E.SPREADS[record.spread].positions.length,prepared=E.prepareDeck(D,record.input.allowReversed!==false),picks=[];
 const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));let phase='shuffle',opened=0;
 resetRitual('กำลังสับไพ่ให้คุณ','กำลังสับไพ่... ตั้งใจถึงคำถามของคุณ');$('ritual').classList.add('tarot-selection');
 const rail=node('div',undefined,'tarot-rail'),fan=node('div',undefined,'tarot-fan');fan.style.width=(prepared.length*44+120)+'px';rail.append(fan);$('ritual-animation').append(rail);
 const cards=prepared.map((item,index)=>{const card=node('button',undefined,'deck-card shuf');card.type='button';card.disabled=true;card.setAttribute('aria-label','ไพ่คว่ำลำดับที่ '+(index+1));card.setAttribute('aria-pressed','false');card.style.setProperty('--i',index);card.style.setProperty('--dx',(E.randomInt(171)-85)+'px');card.style.setProperty('--da',(E.randomInt(27)-13)+'deg');const t=index-(prepared.length-1)/2;card.style.setProperty('--x',(60+index*44)+'px');card.style.setProperty('--y',(45+t*t*.035)+'px');card.style.setProperty('--rot',(t*1.03)+'deg');card.addEventListener('click',()=>pick(index));return card;});fan.append(...cards);rail.scrollLeft=(fan.offsetWidth-rail.clientWidth)/2;
 await wait(2300);if(token!==motion)return;cards.forEach(card=>card.classList.remove('shuf'));fan.classList.add('fanned');phase='fan';await wait(1000);if(token!==motion)return;
 phase='pick';cards.forEach(card=>card.disabled=false);$('ritual-title').textContent='เลือกไพ่ด้วยสัญชาตญาณ';$('ritual-question').textContent='เลือก '+needed+' ใบ · เลื่อนสำรับเพื่อดูไพ่ทั้ง 78 ใบ';$('ritual-selection-count').hidden=false;updateCount();
 function updateCount(){$('ritual-selection-count').textContent='เลือกไพ่ '+needed+' ใบ ด้วยสัญชาตญาณ ('+picks.length+'/'+needed+')';}
 async function pick(index){
  if(phase!=='pick'||token!==motion||picks.includes(index))return;
  picks.push(index);cards[index].classList.add('sel');cards[index].dataset.n=String(picks.length);cards[index].setAttribute('aria-pressed','true');updateCount();
  if(picks.length<needed)return;phase='burn';$('ritual-title').textContent='ไพ่ที่ไม่ได้เลือกกำลังสลายไป...';cards.forEach(card=>card.disabled=true);
  await wait(300);if(token!==motion)return;cards.forEach((card,i)=>{if(!picks.includes(i)){card.style.setProperty('--burn-delay',E.randomInt(351)+'ms');card.classList.add('burn');}});
  await wait(1500);if(token!==motion)return;phase='move';const oldRects=picks.map(i=>cards[i].getBoundingClientRect()),chosen=E.drawPrepared(record.spread,prepared,picks);
  $('ritual-animation').hidden=true;$('ritual-selection-count').hidden=true;$('ritual-backs').classList.add('spread-slots');
  const slots=chosen.map((item,i)=>{const slot=node('button',undefined,'spread-slot');slot.type='button';slot.setAttribute('aria-label','เปิดไพ่ตำแหน่ง'+item.position);slot.append(node('span',item.position,'spread-position'),flipCard(item,i));slot.addEventListener('click',()=>flip(slot,item));return slot;});$('ritual-backs').replaceChildren(...slots);
  slots.forEach((slot,i)=>{const now=slot.getBoundingClientRect(),before=oldRects[i],dx=before.left+before.width/2-now.left-now.width/2,dy=before.top+before.height/2-now.top-now.height/2;slot.animate([{transform:`translate(${dx}px,${dy}px) scale(${before.width/now.width}) rotate(${cards[picks[i]].style.getPropertyValue('--rot')})`},{transform:'none'}],{duration:1000,delay:i*160,easing:'cubic-bezier(.2,.8,.2,1)',fill:'backwards'});});
  await wait(1000+(slots.length-1)*160);if(token!==motion)return;phase='flip';$('ritual-title').textContent='แตะไพ่เพื่อเปิดทีละใบ';$('ritual-question').textContent='ไพ่ที่คุณเลือกอยู่ตรงหน้าแล้ว';
  function flip(slot,item){if(phase!=='flip'||slot.classList.contains('opened'))return;slot.classList.add('opened');slot.querySelector('.ritual-card').classList.add('open');slot.querySelector('.ritual-front').removeAttribute('aria-hidden');slot.setAttribute('aria-label',item.position+' '+D.find(c=>c.id===item.id).name_th);opened++;if(opened===needed){$('ritual-title').textContent='ไพ่ถูกล็อกแล้ว ผลที่เปิดจะไม่เปลี่ยน';$('ritual-question').textContent='';$('reveal').textContent='ดูคำทำนาย ✦';$('reveal').hidden=false;$('reveal').disabled=false;}}
  revealAction=async()=>{if(phase!=='flip'||opened!==needed||token!==motion)return;phase='loading';$('reveal').hidden=true;$('ritual-backs').hidden=true;$('ritual-title').textContent='กำลังอ่านสารจากไพ่';$('reading-loader').hidden=false;const messages=['กำลังรวบรวมพลังของไพ่...','ดวงดาวกำลังเรียงตัว...','กำลังอ่านสารที่ซ่อนอยู่...','ใกล้ได้คำตอบแล้ว...'];let step=0;$('loading-message').textContent=messages[0];const timer=setInterval(()=>{$('loading-message').textContent=messages[++step%messages.length];},1300);await wait(1800);clearInterval(timer);if(token!==motion)return;$('ritual-backs').hidden=false;onComplete(chosen);};
 }
}
$('reveal').addEventListener('click',()=>{if(revealAction)revealAction();});
$('reading-form').addEventListener('submit',async e=>{e.preventDefault();status();try{const entered=input();if(!entered.question){$('question').focus();return;}if(E.triage(entered).crisis)return crisis();const resolved=E.resolveTopic(entered);entered.topic=resolved.topic;entered.topicNote=resolved.note;topic=resolved.topic;document.querySelectorAll('#topic button').forEach(b=>b.setAttribute('aria-pressed',String(b.textContent===({love:'ความรัก',work:'การงาน',money:'การเงิน',self:'ดูแลใจ',general:'ภาพรวม'}[topic]))));const result=E.begin(entered,{...state.history},D);if(result.crisis)return crisis();restored=result.restored;if(restored){current=result.record;state.active=current.key;save();return render();}await selectionRitual(result.record,draw=>{current={...result.record,draw};state.history[current.key]=current;state.active=current.key;save();render();});}catch(err){status(err.message);show('intro');}});
function section(title,text){const s=node('section',undefined,'panel');s.append(node('h3',title),node('p',text));return s;}
async function render(){
 if(!current)return;
 const token=motion;
 let output=E.interpretDirect(current,D),aiError='';if(!output)return crisis();
 if(!current.ai){
  try{
   const cards=current.draw.map(item=>{const card=D.find(c=>c.id===item.id);return {position:item.position,name:card.name_th,reversed:item.reversed,meaning:item.reversed?card.meaning_reversed:card.meaning_upright};});
   const ai=await askAI({kind:'tarot',question:current.input.question,context:current.input.context,topic:current.input.topic,cards});
   if(token!==motion)return;if(ai.crisis)return crisis();
   current.ai=ai;state.history[current.key]=current;save();
  }catch(error){aiError=error.message;}
 }
 if(token!==motion)return;
 if(current.ai){const ai=current.ai;output={...output,cards:output.cards.map((card,i)=>({...card,meaning:ai.cards[i].meaning})),synthesis:ai.overview,advice:{options:[],small_step:ai.advice}};}
 $('spread-title').textContent=E.SPREADS[current.spread].name;
 $('original-question').textContent='“'+current.input.question+'”';
 $('topic-note').textContent=current.input.topicNote||'';$('topic-note').hidden=!current.input.topicNote;
 $('restore-note').textContent=aiError?'ระบบ AI ยังไม่พร้อม จึงแสดงคำอ่านที่เตรียมไว้ · '+aiError:restored?'นี่คือไพ่ชุดเดิมของคำถามนี้ ตำแหน่งและทิศทางยังคงเดิม':'ไพ่ชุดนี้ถูกล็อกไว้สำหรับคำถามของคุณแล้ว';
 const list=$('drawn-cards');list.replaceChildren();
 output.cards.forEach((reading,i)=>{const entry=current.draw[i],card=D.find(c=>c.id===entry.id),article=node('article',undefined,'direct-card'),copy=node('div');article.style.setProperty('--order',i);copy.append(node('p',reading.position,'position'),node('h3',reading.name_th),node('p',reading.name_en+(reading.reversed?' · กลับหัว':''),'orientation'),node('p',reading.meaning));article.append(portrait(card,reading.reversed),copy);list.append(article);});
 const overall=section('✦ คำทำนายภาพรวม',output.synthesis);overall.style.setProperty('--order',output.cards.length);
 const advice=node('section',undefined,'panel');advice.style.setProperty('--order',output.cards.length+1);advice.append(node('h3','✦ คำแนะนำ'));output.advice.options.forEach(line=>advice.append(node('p',line,'advice-line')));advice.append(node('p','สิ่งที่ควรทำตอนนี้: '+output.advice.small_step,'gold-text'));
 $('reading-output').replaceChildren(overall,advice);show('result');
}
$('tarot-new-question').addEventListener('click',()=>{motion++;state.active=null;current=null;save();$('reading-form').reset();topic='love';spread='auto';allowReversed=true;$('reversed').setAttribute('aria-pressed','true');document.querySelectorAll('#topic button').forEach(b=>b.setAttribute('aria-pressed',String(b.textContent==='ความรัก')));document.querySelectorAll('#spread button').forEach(b=>b.setAttribute('aria-pressed',String(b.textContent==='เลือกให้ฉัน')));switchMode('tarot');$('question').focus();});

document.querySelectorAll('[data-home]').forEach(b=>b.addEventListener('click',async()=>{const token=++motion;const page=b.closest('section');if(page)page.classList.add('vanishing');await pause(450);if(token!==motion)return;state.active=null;current=null;save();switchMode(mode);}));
function other(title,eyebrow,content){$('other-title').textContent=title;$('other-eyebrow').textContent=eyebrow;$('other-content').replaceChildren(content);show('other-result');}
async function loadingRitual(title,art,complete){const token=++motion;resetRitual(title);$('ritual-animation').append(art);await pause(1800);if(token!==motion)return;art.classList.add('vanishing');$('reading-loader').hidden=false;await pause(750);if(token!==motion)return;complete();}
let siamsiRun=null;
$('siamsi-start').addEventListener('click',()=>{
 status();const token=++motion;
 resetRitual('เขย่ากระบอกด้วยตัวเอง','ตั้งจิตถึงเรื่องที่อยากทบทวน เขย่ากี่ครั้งก็ได้ แล้วกดหยุดเมื่อใจพร้อม');
 const vessel=cup();$('ritual-animation').append(vessel);
 $('siamsi-shake-controls').hidden=false;
 $('siamsi-shake-count').textContent='เขย่าแล้ว 0 ครั้ง';
 $('siamsi-shake').disabled=false;$('siamsi-stop').disabled=true;
 siamsiRun={token,count:0,vessel,finished:false};
});
$('siamsi-shake').addEventListener('click',()=>{
 const run=siamsiRun;if(!run||run.finished||run.token!==motion||mode!=='siamsi')return;
 run.count++;run.vessel.classList.remove('tap-shake');void run.vessel.offsetWidth;run.vessel.classList.add('tap-shake');
 $('siamsi-shake-count').textContent='เขย่าแล้ว '+run.count+' ครั้ง';
 $('siamsi-stop').disabled=false;
});
$('siamsi-stop').addEventListener('click',async()=>{
 const run=siamsiRun;if(!run||run.finished||!run.count||run.token!==motion||mode!=='siamsi')return;
 run.finished=true;$('siamsi-shake').disabled=true;$('siamsi-stop').disabled=true;$('siamsi-shake-controls').hidden=true;
 await new Promise(r=>setTimeout(r,370));if(run.token!==motion)return;
 run.vessel.classList.remove('tap-shake');
 let result=F.drawFortuneStick();$('ritual-title').textContent='ไม้เซียมซีของคุณกำลังปรากฏ';
 const fallen=node('div',String(result.number).padStart(2,'0'),'falling-stick');fallen.setAttribute('aria-label','ไม้เซียมซีหมายเลข '+result.number);$('ritual-animation').append(fallen);
 await new Promise(r=>setTimeout(r,1350));if(run.token!==motion)return;
 run.vessel.classList.add('vanishing');fallen.classList.add('vanishing');$('reading-loader').hidden=false;
 await new Promise(r=>setTimeout(r,750));if(run.token!==motion)return;
 let aiNotice='';try{const ai=await askAI({kind:'siamsi',stick:result});if(run.token!==motion)return;result={...result,verse:ai.verse,meaning:ai.meaning,advice:ai.advice,method:'บทกลอนและคำอ่านเรียบเรียงโดย AI จากความหมายเซียมซีฉบับอาร์คานา'}}catch(error){aiNotice='ระบบ AI ยังไม่พร้อม จึงแสดงคำอ่านที่เตรียมไว้';}const content=node('div'),slip=node('div',undefined,'fortune-slip');
 slip.append(node('p','บทกลอนเซียมซี','eyebrow'),node('span',String(result.number).padStart(2,'0'),'fortune-number'),node('h3',result.title),node('p',result.verse.join('\n'),'fortune-poem'));
 content.append(slip,section('คำอ่าน',result.meaning),section('สิ่งที่ลองทำได้',result.advice),node('p',result.method+(aiNotice?' · '+aiNotice:''),'method-note'),wallpaperLink(result.wallpaperCategory));
 other('คำทำนายจากเซียมซี','เซียมซี · ใบที่ '+result.number,content);
});
$('birthday-form').addEventListener('submit',e=>{e.preventDefault();status();try{const r=F.birthdayReading({day:Number($('birth-day').value),month:birthMonth,year:Number($('birth-year').value),era:birthEra});const orbit=node('div','☉','birthday-orbit spinning');loadingRitual('กำลังอ่านจังหวะจากวันเกิดของคุณ',orbit,()=>{const c=node('div');c.append(node('div',String(r.number),'birthday-orbit'),section(r.title,r.meaning),section('สิ่งที่นำไปใช้ได้',r.advice),node('p',r.method,'method-note'),wallpaperLink(r.wallpaperCategory,'ภาพที่เข้ากับแนวทางจากวันเกิด'));other('จังหวะของคุณ','เกิด'+r.weekday+' · '+r.dateLabel,c);});}catch(err){status(err.message);}});
function dailyResult(r,restored){const c=node('div'),art=node('div',undefined,'daily-art'),card=D.find(x=>x.id===r.cardId);art.append(portrait(card,r.reversed));c.append(art,node('p',restored?'เปิดแล้ววันนี้ · นี่คือคำอ่านเดิมของคุณ':'บันทึกคำอ่านวันนี้ไว้แล้ว','method-note'),section(r.title,r.meaning),section('ความตั้งใจเล็ก ๆ สำหรับวันนี้',r.advice),wallpaperLink(r.wallpaperCategory));other('ถ้อยคำสำหรับวันนี้',new Intl.DateTimeFormat('th-TH',{dateStyle:'long',timeZone:'Asia/Bangkok'}).format(new Date(r.date+'T12:00:00+07:00')),c);$('daily-start').textContent='อ่านดวงวันนี้อีกครั้ง ✦';}
$('daily-start').addEventListener('click',async()=>{status();try{const token=motion;const {record,restored}=await F.getDailyLocked({storage:localStorage,deck:D});if(token!==motion||mode!=='daily')return;if(restored)return dailyResult(record,true);await tarotRitual([{id:record.cardId,reversed:record.reversed}],'หนึ่งใบสำหรับวันนี้',()=>dailyResult(record,false));}catch(e){status(e.message);}});
const WALLPAPERS={calm:{name:'บัวใต้แสงจันทร์',label:'พักใจและเริ่มใหม่',meaning:'ดอกบัวเป็นสัญลักษณ์ของความบริสุทธิ์และการเติบโตพ้นความขุ่นมัวในศิลปะพุทธ แสงจันทร์ในภาพเติมความสงบ เป็นสิ่งเตือนใจให้คุณค่อย ๆ ดูแลตัวเอง',source:'https://asia.si.edu/interactives/symbols/lotus/index.html',sourceName:'ที่มาสัญลักษณ์ดอกบัว · Smithsonian'},love:{name:'คู่ใจในสระบัว',label:'ความรักและความกลมเกลียว',meaning:'เป็ดแมนดารินคู่และดอกบัวปรากฏในศิลปะจีนในความหมายของความผูกพันและความกลมเกลียว ใช้ภาพนี้เตือนใจให้อ่อนโยน รับฟัง และดูแลความสัมพันธ์ด้วยการกระทำ',source:'https://www.metmuseum.org/art/collection/search/76550',sourceName:'ที่มาสัญลักษณ์เป็ดคู่ · The Met'},prosperity:{name:'สายน้ำแห่งความอุดมสมบูรณ์',label:'ความเพียรและความมั่นคง',meaning:'ปลาคาร์ปสัมพันธ์กับความเพียรและความสำเร็จในคติเอเชียตะวันออก สายน้ำและประกายทองในภาพเป็นการตีความเรื่องความอุดมสมบูรณ์ ชวนให้ค่อย ๆ สร้างฐานชีวิตของตัวเอง',source:'https://investigatingedo.asia.si.edu/lesson-plans/depicting-birds-and-animals/fish/',sourceName:'ที่มาสัญลักษณ์ปลาคาร์ป · Smithsonian'},clarity:{name:'รุ่งอรุณเหนือขุนเขา',label:'เป้าหมายและการเริ่มต้น',meaning:'ภูเขาและแสงรุ่งอรุณถูกตีความทางศิลป์เป็นความมั่นคง เป้าหมาย และการเริ่มใหม่ ภาพนี้เป็นสิ่งเตือนใจให้เดินทีละก้าว ไม่ใช่สูตรมงคลเฉพาะตำรา'}};
function wallpaperLink(category,label='เก็บภาพมงคลที่เข้ากับคำอ่านนี้'){const b=node('button',label+' ↗','recommend-link');b.type='button';b.addEventListener('click',()=>{switchMode('wallpaper');renderWallpaper(category,'แนะนำจากหัวข้อหรือแนวทางในคำอ่านของคุณ');});return b;}
function renderWallpaper(category,reason){const info=WALLPAPERS[category]||WALLPAPERS.calm;lastWallpaper=category;const layout=node('div',undefined,'wallpaper-layout'),img=document.createElement('img'),copy=node('div',undefined,'wallpaper-copy');img.src='assets/wallpapers/'+category+'.png';img.alt=info.name;img.className='wallpaper-preview';copy.append(node('span',info.label,'saved-badge'),node('h3',info.name),node('p',info.meaning),node('p',reason,'method-note'));const download=node('a','ดาวน์โหลดวอลเปเปอร์ ↓','primary-button');download.href=img.src;download.download='arcana-'+category+'.png';copy.append(download,node('p','ไฟล์ภาพแนวตั้งสำหรับมือถือ · 941 × 1672 พิกเซล','quiet-note'));if(info.source){const link=node('a',info.sourceName,'text-button');link.href=info.source;link.target='_blank';link.rel='noopener';copy.append(link);}const again=node('button','สุ่มภาพอื่น','secondary');again.addEventListener('click',()=>randomWallpaper());copy.append(again);layout.append(img,copy);other('ภาพที่อยากอยู่ใกล้คุณ','วอลเปเปอร์มงคล',layout);}
function randomWallpaper(){const pool=Object.keys(WALLPAPERS).filter(x=>x!==lastWallpaper),category=pool[E.randomInt(pool.length)];loadingRitual('กำลังเลือกภาพให้ความตั้งใจของคุณ',node('div','◇','birthday-orbit spinning'),()=>renderWallpaper(category,'สุ่มจากภาพมงคลทั้งสี่ธีม ให้คุณเลือกใช้ภาพที่รู้สึกเชื่อมโยงกับตัวเอง'));}
$('wallpaper-start').addEventListener('click',()=>{status();if(wallpaperTopic==='auto')randomWallpaper();else loadingRitual('กำลังเปิดภาพตามความตั้งใจของคุณ',node('div','◇','birthday-orbit spinning'),()=>renderWallpaper(wallpaperTopic,'เลือกตามความตั้งใจ: '+WALLPAPERS[wallpaperTopic].label));});
const chatMessages=[];
function chatBubble(role,message){const p=node('p',message,'chat-bubble '+role);$('chat-log').append(p);p.scrollIntoView({block:'nearest',behavior:reduced()?'instant':'smooth'});return p;}
$('chat-form').addEventListener('submit',async event=>{
 event.preventDefault();const message=$('chat-input').value.trim();if(!message)return;
 if(E.triage({question:message}).crisis)return crisis();
 const send=$('chat-send');send.disabled=true;$('chat-input').value='';const userBubble=chatBubble('user',message);chatMessages.push({role:'user',content:message});
 const waiting=node('p','กำลังคิดคำตอบ...','chat-bubble assistant');$('chat-log').append(waiting);
 try{const result=await askAI({kind:'chat',messages:chatMessages.slice(-12)});waiting.remove();if(result.crisis)return crisis();chatMessages.push({role:'assistant',content:result.reply});chatBubble('assistant',result.reply);if(result.support)chatBubble('support','หากความรู้สึกนี้รบกวนชีวิตประจำวัน การคุยกับผู้เชี่ยวชาญช่วยได้ โทรสายด่วนสุขภาพจิต 1323 ได้ตลอด 24 ชั่วโมง');}
 catch(error){waiting.textContent='ตอนนี้ยังเชื่อมต่อผู้ช่วย AI ไม่ได้ · '+error.message;chatMessages.pop();userBubble.remove();$('chat-input').value=message;}
 finally{send.disabled=false;$('chat-input').focus();}
});
function modal(content){$('modal-content').replaceChildren(content);$('modal').showModal();}$('close-modal').addEventListener('click',()=>$('modal').close());
$('library-button').addEventListener('click',()=>{const content=node('div');content.append(node('h2','สำรับไพ่ 78 ใบ'),node('p','ไพ่เมเจอร์อาร์คานา 22 ใบ และไพ่ไมเนอร์อาร์คานา 56 ใบ'));const grid=node('div',undefined,'library');D.forEach(c=>{const a=node('article',undefined,'library-card');a.append(portrait(c),node('p',c.keywords_upright.join(' · ')));grid.append(a);});content.append(grid);modal(content);});
$('privacy-button').addEventListener('click',()=>{const content=node('div');content.append(node('h2','พื้นที่ส่วนตัวของคุณ'),node('p','คำถาม บริบท และผลไพ่ทาโรต์เก็บในแท็บนี้ เมื่อใช้คำอ่าน AI หรือแชต ข้อความที่กรอกจะส่งไปยังผู้ให้บริการ AI เพื่อสร้างคำตอบ วันเกิดใช้คำนวณในหน้าเว็บและไม่บันทึกลงประวัติ'),node('p','ดวงรายวันเก็บใน localStorage ของเบราว์เซอร์ โดยเปลี่ยนวันตามเวลาประเทศไทย การล้างข้อมูล เปลี่ยนเบราว์เซอร์ หรือใช้งานแบบส่วนตัวอาจเริ่มผลใหม่ได้ จึงไม่ใช่การยืนยันตัวบุคคล'),node('p','คุกกี้ arcana_privacy จำการตั้งค่า 180 วัน ไม่มีโฆษณาหรือระบบวิเคราะห์ผู้ใช้ แบบอักษรโหลดจาก Google Fonts ซึ่งอาจได้รับข้อมูลการเชื่อมต่อ'),node('p','เมื่อ AI ยังไม่พร้อม ระบบแสดงคำอ่านที่เตรียมไว้ แชตจะไม่ตอบสด ภาพมงคลเป็นความเชื่อและงานศิลป์ ไม่มีการรับรองโชคลาภหรือผลลัพธ์'));const clear=node('button','ลบคำถามไพ่ทาโรต์ในแท็บนี้','secondary');clear.addEventListener('click',()=>{state={history:{},active:null};current=null;save();$('reading-form').reset();$('reading-output').replaceChildren();$('drawn-cards').replaceChildren();$('modal').close();switchMode('tarot');});content.append(clear);modal(content);});
$('cookie-essential').addEventListener('click',()=>{document.cookie='arcana_privacy=essential; Max-Age=15552000; Path=/; SameSite=Lax'+(location.protocol==='https:'?'; Secure':'');$('cookie-banner').hidden=true;});$('cookie-settings').addEventListener('click',()=>$('cookie-banner').hidden=false);$('cookie-banner').hidden=/(?:^|; )arcana_privacy=/.test(document.cookie);
const aiOff=!window.ARCANA_AI_ENDPOINT&&location.hostname.endsWith('github.io');if(aiOff){const chatTab=document.querySelector('[data-mode="chat"]');if(chatTab)chatTab.hidden=true;if(state.mode==='chat')state.mode='tarot';}
if(state.mode&&state.mode!=='tarot')switchMode(state.mode);else if(state.active&&Object.hasOwn(state.history,state.active)){current=state.history[state.active];restored=true;try{render();}catch{state.active=null;save();show('intro');}}
