(function(g){'use strict';
const DISCLAIMER='เพื่อความบันเทิงและการสะท้อนตัวเอง ไม่ใช่การทำนายอนาคต';
const SPREADS={single:{name:'ไพ่หนึ่งใบ',positions:['สารหลัก']},three_card:{name:'เส้นทางสามใบ',positions:['อดีต','ปัจจุบัน','อนาคต']},decision_3:{name:'ทางเลือกสามใบ',positions:['หากดำเนินต่อแบบเดิม','หากเลือกอีกทาง','คำแนะนำ']},five_card:{name:'สำรวจห้าใบ',positions:['สถานการณ์','อุปสรรค','ปัจจัยที่ยังไม่ได้พิจารณา','คำแนะนำ','ผลลัพธ์ที่เป็นไปได้']}};
const normalize=q=>q.normalize('NFKC').toLowerCase().replace(/[\s?？!！。、]+/g,'').trim();
function triage(input){const t=[input.question,input.context,input.said,input.did].filter(Boolean).join(' ');if(/อยากตาย|ไม่อยากอยู่|อยากหายไป|หายไปจากโลก|ทำร้ายตัวเอง|ฆ่าตัวตาย|จบชีวิต|อยู่ไปก็ไม่มี|ไม่ไหวแล้ว.*ชีวิต|suicid|kill myself|self.?harm|end my life|want to die|ไม่อยากมีชีวิต|กรีดข้อมือ|กระโดดตึก|แขวนคอ|กินยาเกินขนาด/i.test(t))return {crisis:true};return {crisis:false,professional:/กินยา|ใช้ยา|ยาอะไร|ยารักษา|หยุดยา|รักษาโรค|โรค|พบหมอ|ผ่าตัด|อาการป่วย|สุขภาพ/.test(t)?'แพทย์หรือเภสัชกร':/ลงทุน|หุ้น|คริปโต|กองทุน|เทรด|ซื้อทอง/.test(t)?'ผู้แนะนำการลงทุนที่มีใบอนุญาต':/คดี|ฟ้อง|กฎหมาย|ศาล|สัญญา|ทนาย/.test(t)?'ทนายความ':null,thirdParty:/เขา|เธอ|อีกฝ่าย|แฟน|will he|will she/i.test(t)&&/รู้สึก|คิด|กลับมา|รัก|นอกใจ|come back|feel/i.test(t)};}
function reframe(input){const q=input.question;if(/กลับมา|come back/i.test(q))return 'ฉันควรเข้าใจอะไรเกี่ยวกับความสัมพันธ์นี้ และอยากทำอะไรต่อ';if(/รอ.*ไหม|รอต่อ/.test(q))return 'ถ้าฉันรอต่อไป กับถ้าฉันดูแลใจตัวเองก่อน อะไรเหมาะกับฉันมากกว่า';if(triage(input).thirdParty)return 'ฉันสังเกตอะไรได้จากสิ่งที่เกิดขึ้น และต้องการขอบเขตแบบไหนสำหรับตัวเอง';if(/ไหม|หรือไม่|จะ.*เมื่อ|จะ.*ได้|อนาคต/.test(q))return 'สำหรับเรื่องที่ถาม ฉันควรพิจารณาอะไร และมีทางเลือกใดที่ลงมือทำได้';return q;}
function pickSpread(i){if(SPREADS[i.spread_choice])return i.spread_choice;return /ควร|หรือ|ดีไหม|ดีมั้ย|เลือก|รอ/.test(i.question)?'decision_3':'three_card';}
function resolveTopic(input){const text=[input.question,input.context].filter(Boolean).join(' '),patterns={love:/รัก|แฟน|คนคุย|เลิกกัน|คิดถึง|ความสัมพันธ์|คู่รัก|คู่ครอง|คู่ชีวิต|จีบ|แต่งงาน|หัวใจ|เดต|เหงา|ชอบเขา/g,work:/งาน|หัวหน้า|ลาออก|สัมภาษณ์|บริษัท|ออฟฟิศ|เลื่อนตำแหน่ง|อาชีพ|ธุรกิจ|ลูกค้า|เพื่อนร่วมงาน|เงินเดือน/g,money:/เงิน(?!เดือน)|การเงิน|ลงทุน|หนี้|หุ้น|ออมเงิน|รายได้|โชคลาภ|หวย/g},labels={love:'ความรัก',work:'การงาน',money:'การเงิน'};const scores=Object.fromEntries(Object.entries(patterns).map(([key,re])=>[key,(text.match(re)||[]).length]));let best=input.topic||'love';for(const key of Object.keys(patterns)){if(scores[key]>(scores[best]||0))best=key;}return {topic:best,note:best!==input.topic?'ปรับหัวข้อเป็น'+labels[best]+'ตามคำถามของคุณ':''};}
function randomInt(max){if(!Number.isInteger(max)||max<1||max>4294967296)throw Error('ช่วงการสุ่มไม่ถูกต้อง');const range=Math.floor(4294967296/max)*max,b=new Uint32Array(1);do{g.crypto.getRandomValues(b);}while(b[0]>=range);return b[0]%max;}
function draw(spread,deck,reversed=true){const d=[...deck];for(let i=d.length-1;i>0;i--){const j=randomInt(i+1);[d[i],d[j]]=[d[j],d[i]];}return SPREADS[spread].positions.map((position,i)=>({id:d[i].id,position,reversed:reversed&&randomInt(2)===1}));}
function shuffleCandidates(deck,count=12){if(!Array.isArray(deck)||new Set(deck.map(c=>c.id)).size!==deck.length||count<1||count>deck.length)throw Error('สำรับไพ่ไม่ถูกต้อง');const d=[...deck];for(let i=d.length-1;i>0;i--){const j=randomInt(i+1);[d[i],d[j]]=[d[j],d[i]];}return d.slice(0,count).map(c=>c.id);}
function prepareDeck(deck,reversed=true){return shuffleCandidates(deck,deck.length).map(id=>({id,reversed:reversed&&randomInt(2)===1}));}
function drawPrepared(spread,prepared,indexes){const positions=SPREADS[spread]?.positions;if(!positions||!Array.isArray(prepared)||!Array.isArray(indexes)||indexes.length!==positions.length||new Set(indexes).size!==indexes.length||indexes.some(i=>!Number.isInteger(i)||i<0||i>=prepared.length))throw Error('การเลือกไพ่ไม่ถูกต้อง');return indexes.map((index,i)=>({...prepared[index],position:positions[i]}));}
function drawSelected(spread,candidates,indexes,reversed=true){const positions=SPREADS[spread]?.positions;if(!positions||!Array.isArray(candidates)||!Array.isArray(indexes)||indexes.length!==positions.length||new Set(indexes).size!==indexes.length||new Set(candidates).size!==candidates.length||indexes.some(i=>!Number.isInteger(i)||i<0||i>=candidates.length))throw Error('การเลือกไพ่ไม่ถูกต้อง');return indexes.map((index,i)=>({id:candidates[index],position:positions[i],reversed:reversed&&randomInt(2)===1}));}
function begin(input,history,deck){if(triage(input).crisis)return {crisis:true};const key=normalize(input.question);if(!key)throw Error('ลองเขียนเรื่องที่อยากทบทวนก่อน');if(Object.hasOwn(history,key))return {record:history[key],restored:true};const spread=pickSpread(input),record={key,input:{...input},spread,draw:draw(spread,deck,input.allowReversed!==false),redraws:0};history[key]=record;return {record,restored:false};}
function redraw(record,spread,deck){if(record.redraws>=1)throw Error('คำถามนี้เปิดไพ่เพิ่มครบแล้ว ลองถามตัวเองว่ากำลังหวังคำตอบแบบไหน และมีอะไรที่ลงมือทำได้โดยไม่ต้องเปิดไพ่อีก');if(!SPREADS[spread]||spread===record.spread)throw Error('เลือกรูปแบบที่ต่างจากเดิม');return {...record,spread,draw:draw(spread,deck,record.input.allowReversed!==false),redraws:1};}
const pos={สารหลัก:'ใช้ประเด็นนี้เป็นจุดเริ่มต้นของการทบทวนวันนี้',อดีต:'ลองมองสิ่งนี้เป็นรากของสถานการณ์ที่ควรทบทวน ไม่ใช่ข้อสรุปว่าอดีตของคุณเป็นอย่างไร',ปัจจุบัน:'ใช้มุมนี้สำรวจสิ่งที่กำลังเกิดขึ้น โดยเทียบกับข้อเท็จจริงที่คุณพบ',อนาคต:'นี่คือทิศทางที่ใช้ชวนคิดหากเงื่อนไขเดิมยังคงอยู่ ไม่ใช่เหตุการณ์ที่จะต้องเกิด',หากดำเนินต่อแบบเดิม:'หากเดินต่อในรูปแบบเดิม ลองพิจารณาทั้งสิ่งที่ได้รับและสิ่งที่ต้องแลก',หากเลือกอีกทาง:'หากลองทางอื่น ใช้ประเด็นนี้คิดถึงสิ่งที่คุณพร้อมเปลี่ยน',คำแนะนำ:'เลือกนำไปใช้เฉพาะส่วนที่ตรงกับสถานการณ์และขอบเขตของคุณ',สถานการณ์:'นี่เป็นกรอบหนึ่งสำหรับมองสถานการณ์ ไม่ใช่ข้อเท็จจริงเพิ่มเติม',อุปสรรค:'ลองตรวจดูว่าประเด็นนี้เป็นข้อจำกัดจริง หรือเป็นสิ่งที่ยังพอปรับได้',ปัจจัยที่ยังไม่ได้พิจารณา:'ใช้สำรวจมุมที่อาจยังไม่ได้คิดถึง ไม่ได้หมายถึงความลับหรือข้อมูลที่ไพ่ค้นพบ',ผลลัพธ์ที่เป็นไปได้:'ใช้เป็นภาพสมมติเพื่อวางแผน ผลจริงขึ้นอยู่กับการกระทำและเงื่อนไขอื่นด้วย'};
const suitNames={cups:'ความรู้สึกและความสัมพันธ์',swords:'ความคิด การสื่อสาร และความขัดแย้ง',wands:'พลังและการลงมือทำ',pentacles:'ทรัพยากร ร่างกาย และความมั่นคง'};
const nums=['','การเริ่มต้น','ทางเลือกและสมดุล','การเติบโตและความร่วมมือ','ความมั่นคงหรือการหยุดนิ่ง','ความขัดแย้งและความท้าทาย','การเปลี่ยนผ่านและการให้รับ','การประเมินและความเพียร','การเคลื่อนไหวและการฝึกฝน','การทบทวนและความยืดหยุ่น','ความสำเร็จหรือภาระที่มากเกิน','ความอยากเรียนรู้','การลงมือทำและความสุดโต่ง','การดูแลจากภายใน','ความรับผิดชอบและการนำ'];
function interpret(record,deck){const input=record.input,safety=triage(input);if(safety.crisis)return null;const cards=record.draw.map(d=>({d,c:deck.find(c=>c.id===d.id)}));const stated=input.context?.trim()||input.question.trim();const output={reframed_question:reframe(input),spread:record.spread,cards:cards.map(({d,c})=>{let core=d.reversed?c.meaning_reversed:c.meaning_upright;const symbol=c.index===13?'ไพ่เดธใช้สื่อถึงการสิ้นสุดและการเปลี่ยนผ่าน ไม่ใช่ความตายหรือคำสาป':c.index===15?'ไพ่เดอะเดวิลเป็นสัญลักษณ์ของความยึดติดและรูปแบบที่เกิดซ้ำ ไม่ใช่คำสาป':c.index===16?'ไพ่เดอะทาวเวอร์เป็นสัญลักษณ์ของการเปลี่ยนแปลงหรือความจริงที่ทำให้ทบทวนฐานเดิม ไม่ใช่ลางร้าย':'';return {position:d.position,name:c.name_th+' ('+c.name_en+')',reversed:d.reversed,meaning:[core,pos[d.position],safety.professional?'ในเรื่องนี้ ใช้ไพ่สำรวจความรู้สึกต่อความไม่แน่นอนเท่านั้น คำตอบเฉพาะทางควรมาจาก'+safety.professional:c.topic_meaning[input.topic]||c.topic_meaning.general,'ข้อควรระวัง: '+c.caution+' จุดแข็งที่นำมาใช้ได้: '+c.resource,symbol].filter(Boolean).join('\n\n'),link_to_user:stated};}),synthesis:'',options:[],one_small_step:'',reflection_question:'หากสถานการณ์ยังเหมือนเดิมอีกสามเดือน คุณอยากดูแลความต้องการข้อไหนของตัวเองก่อน',follow_up_offer:'เพิ่มบริบทด้านล่างเพื่อทบทวนไพ่ชุดเดิมได้ โดยไม่ต้องเปิดไพ่ใหม่',disclaimer:DISCLAIMER};
let lines=[];const feelings=['เหนื่อย','เสียใจ','กังวล','สับสน','กลัว','เหงา','เจ็บ','ดีใจ'].filter(f=>stated.includes(f));lines.push(feelings.length?'คุณเล่าว่ามีความรู้สึก'+feelings.join('และ')+'อยู่ด้วย ลองให้พื้นที่กับความรู้สึกนี้ก่อนรีบหาข้อสรุป':'ขอบคุณที่แบ่งปันเรื่องที่อยากทบทวน คุณไม่จำเป็นต้องหาคำตอบทั้งหมดในครั้งเดียว');if(safety.thirdParty)lines.push('ไพ่ไม่สามารถบอกความคิดหรือความรู้สึกของอีกฝ่ายได้ จึงชวนมองสิ่งที่คุณสังเกตได้ ความต้องการของคุณ และทางเลือกที่อยู่ในมือคุณ');if(safety.professional)lines.push('เรื่องนี้ควรปรึกษา'+safety.professional+' คำอ่านนี้ใช้สะท้อนความรู้สึกเท่านั้น ไม่ใช้เลือกการรักษา แนวทางคดี หรือการลงทุน');
lines.push(cards.map(({d,c})=>d.position+': '+(d.reversed?c.keywords_reversed:c.keywords_upright).slice(0,2).join('และ')).join(' → '));const tags=cards.flatMap(x=>x.c.tags||[]);if((tags.includes('move')&&tags.includes('pause'))||(tags.includes('change')&&tags.includes('stability')))lines.push('ไพ่มีประเด็นที่ขัดแย้งกันอยู่ ทั้งการเดินหน้าหรือเปลี่ยนแปลง และการชะลอหรือรักษาความมั่นคง ไม่จำเป็นต้องฝืนให้เป็นคำตอบเดียว ลองมองเป็นทางเลือกที่มีข้อแลกเปลี่ยนต่างกัน');if(cards.length>1&&cards.filter(x=>x.c.arcana==='major').length>cards.length/2)lines.push('ไพ่เมเจอร์อาร์คานาปรากฏหลายใบ จึงชวนทบทวนคุณค่าและภาพรวมของชีวิต มากกว่าจะติดอยู่กับเหตุการณ์เดียว');for(const [s,n] of Object.entries(suitNames)){if(cards.filter(x=>x.c.suit===s).length>=2)lines.push('ไพ่ชุดเดียวกันปรากฏซ้ำ โดยเน้นเรื่อง'+n);}for(let n=1;n<=14;n++){if(cards.filter(x=>x.c.arcana==='minor'&&x.c.number===n).length>=2)lines.push('ลำดับไพ่ที่ซ้ำกันชวนพิจารณาเรื่อง'+nums[n]);}if(cards.filter(x=>x.d.reversed).length>cards.length/2)lines.push('ไพ่กลับหัวหลายใบชวนมองกระบวนการภายใน สิ่งที่ติดขัด หรือจังหวะที่ต้องใช้เวลา ไม่ได้แปลว่าจะเกิดเรื่องไม่ดี');if(/ไร้ค่า|ไม่มีค่า|พิสูจน์.*คุณค่า/.test(stated))lines.push('การรอหรือผลตอบรับจากคนอื่นไม่ใช่สิ่งที่ตัดสินคุณค่าของคุณ');output.synthesis=lines.join('\n\n');if(input.said?.trim()&&input.did?.trim())output.say_vs_do='สิ่งที่คุณเล่าว่าอีกฝ่ายพูด: “'+input.said.trim()+'”\nสิ่งที่คุณสังเกตว่าอีกฝ่ายทำ: “'+input.did.trim()+'”\nสองส่วนนี้อาจสอดคล้องหรือต่างกัน ลองพิจารณาจากเหตุการณ์ที่เกิดขึ้น โดยยังไม่สรุปเจตนาของอีกฝ่าย';
output.options=[{path:'เดินต่อพร้อมกำหนดขอบเขต',what_cards_suggest:cards[0].c.name_th+' ชวนใช้จุดแข็งนี้: '+cards[0].c.resource+' ลองเขียนเงื่อนไขที่คุณรับได้ก่อนตัดสินใจ'},{path:'ทดลองเปลี่ยนสิ่งเล็ก ๆ ที่ควบคุมได้',what_cards_suggest:cards[cards.length-1].c.name_th+' ชวนระวังว่า '+cards[cards.length-1].c.caution+' เลือกปรับเพียงเรื่องเดียวแล้วสังเกตผล'},{path:'พักการตัดสินใจเพื่อรวบรวมข้อมูล',what_cards_suggest:'ใช้ประเด็นจาก'+cards[0].c.name_th+' จดสิ่งที่รู้จริงแยกจากสิ่งที่คาด แล้วเลือกคนที่ช่วยให้ข้อมูลได้'}];output.one_small_step=safety.professional?'วันนี้ลองจดข้อกังวลและคำถามหนึ่งข้อ เพื่อนำไปคุยกับ'+safety.professional:cards[cards.length-1].c.small_step;return output;}
function interpretDirect(record,deck){
 const input=record.input,safety=triage(input);if(safety.crisis)return null;
 const topicNames={love:'ความรัก',work:'การงาน',money:'การเงิน',self:'การดูแลตัวเอง',general:'ภาพรวมชีวิต'};
 const chosen=record.draw.map(d=>({d,c:deck.find(c=>c.id===d.id)}));
 const clean=text=>String(text||'').replace(/[^.!?\n]*[?？]/g,'').replace(/ลองถามใจตัวเอง|ลองถามว่า|ถามตัวเอง/g,'พิจารณาว่า').trim();
 const positionLine=position=>({อดีต:'สิ่งนี้เป็นรากของเรื่องที่คุณกำลังเผชิญ',ปัจจุบัน:'พลังของไพ่กำลังสะท้อนสิ่งที่เกิดขึ้นในช่วงนี้',อนาคต:'ในระยะสั้นแนวโน้มนี้จะเด่นขึ้นหากเงื่อนไขยังเหมือนเดิม',สารหลัก:'นี่คือประเด็นหลักที่ไพ่ชวนให้คุณเห็น',คำแนะนำ:'ไพ่ใบนี้ชี้ทางลงมือที่ยังอยู่ในมือคุณ',สถานการณ์:'ไพ่ใบนี้สะท้อนสภาพของเรื่องในเวลานี้',อุปสรรค:'จุดติดขัดนี้ยังมีทางคลี่คลาย',ผลลัพธ์ที่เป็นไปได้:'นี่คือแนวโน้มหนึ่งในระยะสั้น ไม่ใช่ผลลัพธ์ที่ตายตัว'})[position]||'ไพ่ใบนี้เพิ่มอีกมุมหนึ่งให้เรื่องที่คุณถาม';
 const cards=chosen.map(({d,c})=>{const core=clean(d.reversed?c.meaning_reversed:c.meaning_upright),topic=clean(c.topic_meaning[input.topic]||c.topic_meaning.general),symbol=c.index===13?'ไพ่เดธหมายถึงการเปลี่ยนผ่าน ไม่ใช่ความตายหรือคำสาป':c.index===15?'ไพ่เดอะเดวิลหมายถึงความยึดติด ไม่ใช่คำสาป':c.index===16?'ไพ่เดอะทาวเวอร์หมายถึงความจริงหรือการเปลี่ยนฉับพลัน ไม่ใช่ลางร้าย':'';return {position:d.position,name_th:c.name_th,name_en:c.name_en,reversed:d.reversed,meaning:['ไพ่'+c.name_th+(d.reversed?' (กลับหัว)':'')+' บอกว่า '+core,positionLine(d.position),topic,symbol].filter(Boolean).join(' ')};});
 const first=chosen[0],last=chosen.at(-1);
 let synthesis='สำหรับเรื่อง'+(topicNames[input.topic]||'ที่คุณถาม')+' '+(chosen.length===1?'ไพ่ใบนี้':'ไพ่ชุดนี้')+'ชวนให้มองสถานการณ์จากหลายด้านก่อนตัดสินใจ คุณอาจยังไม่ต้องจัดการทุกอย่างพร้อมกัน เลือกสิ่งที่อยู่ในมือแล้วค่อยทำทีละเรื่อง ผลลัพธ์ยังขึ้นอยู่กับการตัดสินใจของคุณและเงื่อนไขรอบตัว';
 if(safety.thirdParty)synthesis+=' ไพ่ไม่ได้ยืนยันความคิดลับของอีกฝ่าย แต่สะท้อนทิศทางที่คุณสังเกตได้จากความสัมพันธ์';
 if(safety.professional)synthesis='เรื่อง'+(topicNames[input.topic]||'นี้')+'ที่คุณถามควรใช้ข้อมูลจาก'+safety.professional+'ประกอบการตัดสินใจ ไพ่ชุดนี้สะท้อนความรู้สึกและทางเลือกที่อยู่ในมือคุณ ไม่ใช้แทนคำแนะนำเฉพาะทาง';
 const advice={options:[clean(first.c.resource),clean(last.c.caution)],small_step:clean(safety.professional?'จดข้อกังวลที่ชัดที่สุดหนึ่งข้อแล้วนำไปคุยกับ'+safety.professional:last.c.small_step)};
 return {cards,synthesis:clean(synthesis),advice,disclaimer:DISCLAIMER};
}
const api={DISCLAIMER,SPREADS,normalize,triage,reframe,pickSpread,resolveTopic,randomInt,draw,shuffleCandidates,prepareDeck,drawPrepared,drawSelected,begin,redraw,interpret,interpretDirect};if(typeof module!=='undefined')module.exports=api;else g.TarotReader=api;
})(globalThis);
